[create_a_thing]
name = "Create a thing"
uri = "{{ .host }}/things/"
method = "POST"
body = """
{
  "hello": "world",
  "works": false
}
"""
	[create_a_thing.headers]
	Authorization = ["Bearer sample_bearer_token"]

	[create_a_thing.assert]
		[create_a_thing.assert.response]
		code = 200
		body = '{"id": 0}'
		[create_a_thing.assert.response.headers]
		Content-Type = ["application/json"]

[read_a_thing]
name = "Read a thing"
uri = "{{ .host }}/things/${ json .create_a_thing `id` }"
method = "GET"
	[read_a_thing.headers]
	Authorization = ["Bearer sample_bearer_token"]

	[read_a_thing.assert]
		[read_a_thing.assert.response]
		code = 200
		[read_a_thing.assert.jsonschema]
		ref = "examples/thing.json"

[delete_a_thing]
name = "Read a thing"
uri = "{{ .host }}/things/${ json .create_a_thing `id` }"
method = "DELETE"
	[delete_a_thing.headers]
	Authorization = ["Bearer sample_bearer_token"]

	[delete_a_thing.assert]
		[delete_a_thing.assert.response]
		code = 201

[read_a_missing_thing]
name = "Read a missing thing"
uri = "{{ .host }}/things/${ json .create_a_thing `id` }"
method = "GET"
	[read_a_missing_thing.headers]
	Authorization = ["Bearer sample_bearer_token"]

	[read_a_missing_thing.assert]
		[read_a_missing_thing.assert.response]
		code = 404
